### ISSUE TITLE
BUG

### ISSUE THREAD

**Issue by 24Kavisha** [Share-Impact/iOS-Impact-Issues#7]
**Describe the bug**
Amount raised is not displayed in the JLL leaderboard.

**To Reproduce**
1. Start the app
2. Start thee non- impact workout
3. End workout
4. Cant find workout in Leaderboard

**Expected behavior**

Workout should be displayed on the leaderboard

**Screenshots**
![img_1589263076034](https://user-images.githubusercontent.com/64829704/81690982-ba8d5680-9479-11ea-8afa-310946bc9770.jpeg)
![img_1589263153220](https://user-images.githubusercontent.com/64829704/81691062-d8f35200-9479-11ea-8020-6540e7b5cda8.jpeg)

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**
 - Device: iPhone 11
 - OS: 13.4.1
 - Version 3.5.25

**Additional context**

**Comment by nik6018** [comment]
Since this league has distance as it main metric the amount raised for a person  was `null` from the backend.

The check on the iOS app expected distance & amount to be != null and then decide on showing the metric as distance or rupees.

As the amount was `null` from the backend this checked failed and the default value of "--" was shown.

After discussing with the backend team, the amount will sent as `0` instead of `null` if the user has not raised any money.

This issue will be resolved once the user pull's to refresh the leaderboard.
